Correct bash command for kubectl apply
Fix command syntax for applying ProvisioningRequest.
In step2  at line80 there is a missing "-" after the kubectl apply -f command, this results in this error
error: flag needs an argument: 'f' in -f
See 'kubectl apply --help' for usage.

This "-" fix the issue.